### ISSUE TITLE
Still Syncing to Server

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#3]
Not sure if this is a crash but I did the following

1. Copying one of the plans (not the main plan)
2. Modify name
3. Make some changes to essential and discretionary spending
4. Select View All Plans
5. Result see screenshot below

![image](https://github.com/bengmathew/tpaw/assets/7815095/c7921e0b-7293-4d84-b64c-0ee65a871547)

After killing the tab with the tpaw app and opening a new tab with the tpaw app I noticed that my last change (an update to discretionary spending was not saved)

**Comment by bengmathew** [comment]
Thanks for reporting this.

This happens when you trigger a navigation away from a plan while updates are still being pushed to the server. Normally the "syncing" message will disappear quickly and be replaced by a message saying it is safe to navigate. If the syncing state persisted then it means there was an issue with the network call. That explains why the last update didn't show up when you reloaded.

I want to say this is a transient network issue, but I would like to keep an eye on it. It happened once to us during our testing. If it is not too much trouble can you be on the lookout for this issue and let us know how many times it happens for you in the next week or two?

If it happens often, we can dig deeper into why the network call failed, or at least have a more graceful UI to handle this situation.

**Comment by michielveen** [comment]
Have not seen this anymore.

**Comment by bengmathew** [comment]
Thanks for following up. If it happens again, please reopen the issue.

**Comment by bengmathew** [comment]
We've improved the way in which syncing to the server happens. We've also improved the UI for handling problems when they arise. The UI will now:
-  communicate that there is a sync issue more promptly
-  stop the user from continuing to make changes that are not being saved
-  provide the ability to manually retry syncing, or abort and lose changes

The pop-up that will show up when there is an issue:

![pic_sync error](https://github.com/bengmathew/tpaw/assets/92544101/0c7a6569-9afb-451c-87fd-0cece9722180)
